name: catlogger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase: ^9.0.3
  cloud_firestore: ^5.6.6
  flutter_launcher_icons: ^0.14.3
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  go_router: ^15.1.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
